export type AccuredCarryInputGlobalModel ={
    globalAccuredCarryId: number,
    fmInvId: string,
    tfInvestor: string,
    grossProceeds: string,
    withholdingForExpenses: string,
    returnOfCapital: string,
    returnOfExpenses: string,
    netting: string,
    netGain: string,
    fairMarketValue: string,
    unrealizedExpenses: string,
    remainingInvestedCapital: string,
    adjCumNetGain: string,
    prefTarget: string,
    prefPaid: string,
    _0ToLp: string,
    _100ToGp: string,
    _80ToLp: string,
    _20ToGp: string,
    cumGpCarry: string,
    ltdCarryPaid: string,
    eligibleCarry: string,
    currentCarry: string,
    totalAccruedCarryForGp: string,
    totalCumNetGainForLp: string,
}