export type DistributionOutputGlobalModel =
{   
tenaskaSaleWaterfallOutputId: number,
fmInvId:number,
tfInvestor:string,
grossProceeds: number,
withholdingForExpenses: number,
grossGain: number,
returnOfCapital: number,
returnOfExpenses: number,
netting: number,
cumGainSubjToCarry: number,
prefTarget: number,
prefPaid: number,
addlGainReqdForCatchUp: number,
_0ToLp: number,
_100ToGp: number,
_80ToLp: number,
_20ToGp: number,
cumGpCarry: number,
ltdCarryPaid: number,
eligibleCarry: number,
currentCarry: number,
distributionToLp: number,
}
